### ISSUE TITLE
Face error during completion 

### ISSUE THREAD

**Issue by anuragpindoriya** [Tomoms/android_kernel_motorola_sm6225-old#1]
CC [M]  drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.o
../drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.c:49:10: fatal error: 'include/firmware/fw_sample.i' file not found
#include FTS_UPGRADE_FW_FILE
         ^~~~~~~~~~~~~~~~~~~
../drivers/input/touchscreen/focaltech_touch_v3/focaltech_config.h:301:49: note: expanded from macro 'FTS_UPGRADE_FW_FILE'
#define FTS_UPGRADE_FW_FILE                     "include/firmware/fw_sample.i"
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [../scripts/Makefile.build:338: drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.o] Error 1
make[4]: *** [../scripts/Makefile.build:642: drivers/input/touchscreen/focaltech_touch_v3] Error 2
make[3]: *** [../scripts/Makefile.build:642: drivers/input/touchscreen] Error 2
make[2]: *** [../scripts/Makefile.build:642: drivers/input] Error 2
make[1]: *** [/home/runner/work/android_kernel_motorola_sm6225_tom/android_kernel_motorola_sm6225_tom/Makefile:1246: drivers] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      techpack/video/msm/vidc/msm_vidc.o
  
  how i fix this error can anyone help me 
  
  @Tomoms

**Comment by Tomoms** [comment]
Are you building for rhode?

**Comment by anuragpindoriya** [comment]
> Are you building for rhode?

Yas

**Comment by anuragpindoriya** [comment]
I compile kernel  with proton-clang for " Rhode " and branch is 't'

and i encounter below error 

--------------------------------------------------------------------------------------------------------------------
 CC      kernel/cgroup/cgroup.o
  CC      mm/vmscan.o
../mm/vmscan.c:5195:2: error: #else after #else
#else
 ^
../mm/vmscan.c:2557:2: error: unterminated conditional directive
#ifdef CONFIG_LRU_GEN
 ^
2 errors generated.
make[2]: *** [../scripts/Makefile.build:338: mm/vmscan.o] Error 1
make[1]: *** [/home/runner/work/android_kernel_motorola_sm6225_tom/android_kernel_motorola_sm6225_tom/Makefile:1241: mm] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      kernel/cgroup/rstat.o
  CC      kernel/cgroup/namespace.o
  -----------------------------------------------------------------------------------------------------------------------
  
  @Tomoms can you help me , here is full log 
  
  https://github.com/anuragpindoriya/android_kernel_motorola_sm6225_tom/actions/runs/6695174846/job/18190136576

**Comment by Tomoms** [comment]
Yeah, that's a merge error which I fixed, but I forgot to push the new commit. Look at this commit: https://github.com/Tomoms/android_kernel_motorola_sm6225/commit/7c827ca0260b07579c67866cf04e80059c458001
Just replace `#else` with `#endif` and you will be good to go! Or, wait a few hours, and I'll push the fixed commit.

**Comment by anuragpindoriya** [comment]
> Yeah, that's a merge error which I fixed, but I forgot to push the new commit. Look at this commit: [7c827ca](https://github.com/Tomoms/android_kernel_motorola_sm6225/commit/7c827ca0260b07579c67866cf04e80059c458001) Just replace `#else` with `#endif` and you will be good to go! Or, wait a few hours, and I'll push the fixed commit.

It's work

**Comment by anuragpindoriya** [comment]
And encounter new issue 

  CC [M]  drivers/input/touchscreen/focaltech_touch_v3/focaltech_point_report_check.o
  CC      techpack/display/msm/dsi/dsi_ctrl_hw_2_0.o
  CC [M]  drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.o
  CC      techpack/display/msm/dsi/dsi_ctrl_hw_2_2.o
../drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.c:49:10: fatal error: 'include/firmware/fw_sample.i' file not found
#include FTS_UPGRADE_FW_FILE
         ^~~~~~~~~~~~~~~~~~~
../drivers/input/touchscreen/focaltech_touch_v3/focaltech_config.h:301:49: note: expanded from macro 'FTS_UPGRADE_FW_FILE'
#define FTS_UPGRADE_FW_FILE                     "include/firmware/fw_sample.i"
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [../scripts/Makefile.build:338: drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.o] Error 1
make[4]: *** [../scripts/Makefile.build:642: drivers/input/touchscreen/focaltech_touch_v3] Error 2
make[3]: *** [../scripts/Makefile.build:642: drivers/input/touchscreen] Error 2
make[2]: *** [../scripts/Makefile.build:642: drivers/input] Error 2
make[1]: *** [/home/runner/work/android_kernel_motorola_sm6225_tom/android_kernel_motorola_sm6225_tom/Makefile:1241: drivers] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      techpack/display/msm/dsi/dsi_ctrl.o
  CC      techpack/display/msm/dsi/dsi_catalog.o


For more log 

https://github.com/anuragpindoriya/android_kernel_motorola_sm6225_tom/actions/runs/6705508684/job/18220102467

@Tomoms 

It's a main error we encounter and start this issue and after we still here what a stubborn error 🤣🤣

**Comment by FPSensor** [comment]
I just did a build with clang 17.0.2 and faced 0 errors

**Comment by anuragpindoriya** [comment]
> I just did a build with clang 17.0.2 and faced 0 errors

Can you compile kernel using github workflow so it's easy to see logs

**Comment by FPSensor** [comment]
> > I just did a build with clang 17.0.2 and faced 0 errors
> 
> Can you compile kernel using github workflow so it's easy to see logs

Why want logs of a build with 0 errors

**Comment by anuragpindoriya** [comment]
> > > I just did a build with clang 17.0.2 and faced 0 errors
> > 
> > Can you compile kernel using github workflow so it's easy to see logs
> 
> Why want logs of a build with 0 errors 

Ok , give which toolchin you use

**Comment by anuragpindoriya** [comment]
> > > > I just did a build with clang 17.0.2 and faced 0 errors
> > > 
> > > Can you compile kernel using github workflow so it's easy to see logs
> > 
> > Why want logs of a build with 0 errors 
> 
> Ok , give which toolchin you use 

@FPSensor

**Comment by Tomoms** [comment]
> Ok , give which toolchin you use

I use this one: https://gitlab.com/Kenvyra/android_prebuilts_clang_host_linux-x86
(clang 16, so the clang-r475365b folder)

**Comment by FPSensor** [comment]
> > Ok , give which toolchin you use
> 
> I use this one: https://gitlab.com/Kenvyra/android_prebuilts_clang_host_linux-x86 (clang 16, so the clang-r475365b folder)

I use this  https://gitlab.com/FPSensor/clang_r487747x
r487747c

**Comment by anuragpindoriya** [comment]
> > I use this one: https://gitlab.com/Kenvyra/android_prebuilts_clang_host_linux-x86 (clang 16, so the clang-r475365b folder)
> 
> I use this https://gitlab.com/FPSensor/clang_r487747x r487747c

i use both toolchain but compile field at 

 CC [M]  drivers/input/touchscreen/goodix_berlin_mmi/goodix_brl_fwupdate.o
../drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.c:49:10: fatal error: 'include/firmware/fw_sample.i' file not found
#include FTS_UPGRADE_FW_FILE
         ^~~~~~~~~~~~~~~~~~~
../drivers/input/touchscreen/focaltech_touch_v3/focaltech_config.h:301:49: note: expanded from macro 'FTS_UPGRADE_FW_FILE'
#define FTS_UPGRADE_FW_FILE                     "include/firmware/fw_sample.i"
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [../scripts/Makefile.build:338: drivers/input/touchscreen/focaltech_touch_v3/focaltech_flash.o] Error 1

can you show me your build script or any build instruction so i getting where i make mistake 
@Tomoms @FPSensor

**Comment by anuragpindoriya** [comment]
@Tomoms @FPSensor  while compile only kernel still i face this issue

**Comment by ZetLink** [comment]
The same error tells you that you are missing files. It usually occurs when the `make mrproper` command is executed.

I recommend you download the files from the following repository.
https://github.com/LineageOS/android_kernel_motorola_sm6225

**Comment by Tomoms** [comment]
I have redone my kernel from scratch, is this still happening?

**Comment by ZetLink** [comment]
It only happened to me with builds based on Android 14 February patch. I did a fork of your new kernel and didn't have that problem. Neither with the one in the LOS repositories.
